routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('profil','ProfileController@index')->name('profil');
Route::get('profil/{page}','ProfileController@index');
Route::get('profil/detail/{id}','ProfileController@detail');

// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::resource('user', 'DataController');
    Route::get('user/delete/{id}', 'DataController@delete');
    Route::get('image/delete/{id}', 'DataController@deleteImage');
    Route::get('file/delete/{id}', 'DataController@deleteFile');
    Route::get('user_getData','DataController@getData')->name('user_getData');

    Route::resource('admin', 'AdminController');
    Route::get('admin/delete/{id}', 'AdminController@delete');
    Route::get('admin_getData','AdminController@getData')->name('admin_getData');

    Route::resource('setting', 'SettingController');
    Route::get('setting/delete/{id}', 'SettingController@delete');
    Route::get('setting_getData','SettingController@getData')->name('setting_getData');
    Route::post('setting/toggleActive','SettingController@toggleActive')->name('setting_toggleActive');

});

app/Setting.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Setting extends Model
{
    //
    protected $table = 'setting';

    protected $fillable = [
        'key',
        'desc',
        'value',
        'type',
        'status',
    ];
}

app/Http/Controllers/SettingController.php
<?php

namespace App\Http\Controllers;

use Validator;
use DB;

use Illuminate\Http\Request;
Use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Storage;

use App\Setting;

use Yajra\Datatables\Datatables;
use Carbon\Carbon;

class SettingController extends Controller
{
    //
    public function index(){
        return view('admin.module.setting.index');
    }

    public function create(){
        return view('admin.module.setting.create');
    }

    public function store(Request $request){
        $messages = [
            'key.required' => 'Key tidak boleh kosong',
            // 'value.required' => 'Value tidak boleh kosong',
            'type.required' => 'Tipe tidak boleh kosong',
            'key.unique' => 'Key sudah terdaftar di database',            
        ];  
        $validator = Validator::make($request->input(), array(
            "key"           => 'required|unique:setting',
            // "value"         => 'required',
            "type"         => 'required',
        ), $messages);
        
        if ($validator->fails()) {
            return response()->json([
                'message'   => $validator->errors(),
                'status'    => false
            ], 400);
        }

        try {
            DB::beginTransaction();

            if($request->type == 'file'){
                $destination = 'public/setting/';
                if ($request->hasFile('file'))
                {
                    if (!file_exists(storage_path($destination))) {
                        Storage::makeDirectory($destination);
                    }                    
                                        
                    $file = $request->file('file');
                    $file_name = md5($file->getClientOriginalName())."_unique_".uniqid().".".$file->getClientOriginalExtension();
                    $file->storeAs($destination, $file_name);
                    $value = 'setting/'.$file_name;
                }
            }
            else{
                $value = $request->value;
            }            

            Setting::create([
                'key' => $request->key,
                'desc' => $request->desc,
                'type' => $request->type,
                'value' => $value,
                'status' => 1,
            ]);

            DB::commit();
            return response()->json(['status' => true]);
        } catch (\Throwable $th) {
            DB::rollback();
            return response()->json(['status' => false, 'message' => $th->getMessage()], 400);
        }
    }

    public function show($id){
        $data = Setting::find($id);
        return view('admin.module.setting.show',compact('data'));
    }

    public function edit($id){
        $data = Setting::find($id);
        return view('admin.module.setting.edit',compact('data'));
    }

    public function update($id,Request $request){
        $messages = [
            // 'key.required' => 'Key tidak boleh kosong',
            // 'value.required' => 'Value tidak boleh kosong',
            // 'key.unique' => 'Key sudah terdaftar di database',            
        ];  
        $validator = Validator::make($request->input(), array(
            // "key"           => 'required|unique:setting,key,'.$id,
            // "value"         => 'required',
        ), $messages);

        if ($validator->fails()) {
            return response()->json([
                'message'   => $validator->errors(),
                'status'    => false
            ], 400);
        }

        try {
            DB::beginTransaction();

            if(Setting::find($id)->type == 'file'){
                $destination = 'public/setting/';
                if ($request->hasFile('file'))
                {
                    if (!file_exists(storage_path($destination))) {
                        Storage::makeDirectory($destination);
                    }                    
                                        
                    $file = $request->file('file');
                    $file_name = md5($file->getClientOriginalName())."_unique_".uniqid().".".$file->getClientOriginalExtension();
                    $file->storeAs($destination, $file_name);
                    $value = 'setting/'.$file_name;
                }else{
                    $value = Setting::find($id)->value;
                }
            }
            else{
                $value = $request->value;
            }            


            Setting::find($id)->update([
                // 'key' => $request->key,
                'desc' => $request->desc,
                'value' => $value,
            ]);            

            DB::commit();
            return response()->json(['status' => true]);
        } catch (\Throwable $th) {
            DB::rollback();
            return response()->json(['status' => false, 'message' => $th->getMessage()], 400);
        }
    }

    public function delete($id){
        try {
            Setting::find($id)->delete();
            return response()->json(['status' => true]);
        } catch (\Throwable $th) {
            return response()->json(['status' => false, 'message' => $th->getMessage()], 400);
        }   
    }

    public function getData(){
        $query = Setting::select('*')->latest();
        return Datatables::of($query)
        ->addIndexColumn()        
        ->editColumn('status', function($data){
            $value = $data->status == 1 ? 'checked' : '';
            return "<input type='checkbox' $value data-bootstrap-switch data-size='xs' data-id='".$data->id."' >";
        })
        ->addColumn('action', function($data){
            return "
                <a href=".url('setting/'.$data->id)."><button class='btn btn-sm btn-secondary'><i class='fa fa-eye'></i><span class='d-none d-sm-inline'> Lihat</span></button></a>
                <a href=".url('setting/'.$data->id.'/edit')."><button class='btn btn-sm btn-success'><i class='fa fa-edit'></i><span class='d-none d-sm-inline'> Edit</span></button></a>
                <button onclick='del(".$data->id.",`".$data->username."`)' class='btn btn-sm btn-danger'><i class='fa fa-trash'></i><span class='d-none d-sm-inline'> Hapus</span></button>
            ";
        })
        ->rawColumns([
            'action','status'
        ])
        ->make(true);   
    }

    public function toggleActive(Request $request){
        try {            
            $status = $request->status == "true" ? 1 : 0 ;
            Setting::find($request->id)->update(['status' => $status]);
            return response()->json(['status'=>true]);
        } catch (\Throwable $th) {
            return response()->json(['status'=>false], 400);
        }
    }
}

resources/views/admin/module/setting/create.blade.php
@extends('admin.layouts.app', ['active' => 'Pengaturan'])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Pengaturan</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('setting.index') }}">Pengaturan</a></li>
            <li class="breadcrumb-item active">Create</a></li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="nav-icon fas fa-cog"></i> Tambah Pengaturan</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('setting.store') }}" method="post" class="form-horizontal" id="formData" enctype="multipart/form-data">
                @csrf                

                <div class="form-group row">
                    <label for="key" class="col-sm-2 col-form-label">Key</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="key" name="key" placeholder="Key" autocomplete="off" value="">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="key" class="col-sm-2 col-form-label">Tipe</label>
                    <div class="col-sm-10">
                      <select name="type" id="type" class="form-control" onchange="show(this.value)">
                          <option value="" selected disabled hidden>Pilih tipe</option>
                          <option value="text">Text</option>
                          <option value="file">File</option>
                      </select>
                    </div>
                </div>                        

                <div id="type_text" class="form-group row type_value" style="display: none">
                    <label for="value" class="col-sm-2 col-form-label">Value</label>
                    <div class="col-sm-10">
                      <textarea name="value" id="value" cols="20" rows="5" class="form-control" placeholder="Value"></textarea>
                    </div>
                </div>

                <div id="type_file" class="form-group row type_value" style="display: none">
                    <label for="value" class="col-sm-2 col-form-label">File</label>
                    <div class="col-sm-10">
                      <input type="file" name="file" id="file" class="form-control">
                    </div>
                </div>
                
                <div class="form-group row">
                    <label for="desc" class="col-sm-2 col-form-label">Deskripsi <small>*Optional</small> </label>
                    <div class="col-sm-10">
                        <textarea name="desc" id="desc" cols="20" rows="5" class="form-control" placeholder="Keterangan"></textarea>
                    </div>
                </div>

                <div class="float-right">
                    <button id="submit" class="btn btn-success" type="submit">Simpan</button>
                </div>

            </form> 
        </div>    
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->


@endsection

@section('javascripts')
<script>
    const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 5000
    });    

    function show(value){
        $('.type_value').hide();
        $('#type_'+value).fadeIn();
    }
    
    $(document).ready(function(){        

        $('#formData').submit(function(e){
            e.preventDefault();            
            $('#submit').attr('disabled', true);
            $('#submit').html('Menyimpan <i class="fas fa-sync-alt fa-spin"></i>');   
            var formData = new FormData($(this)[0]);
            $.ajax({
                method : $(this).attr('method'),
                url : $(this).attr('action'),
                data : formData,
                processData: false,
                contentType: false,
                success : function(data){
                    $('#submit').attr('disabled', false);
                    $('#submit').html('Simpan');
                    Swal.fire(
                        'Selesai!',
                        'Data berhasil disimpan.',
                        'success'
                    )
                    $('#formData').trigger("reset");
                    $('.type_value').hide();
                },
                error: function(err){
                    $('#submit').attr('disabled', false);
                    $('#submit').html('Simpan');                    
                    var response = JSON.parse(err.responseText);
                    
                    var errorString = '';
                    if(typeof response.message === 'object'){
                        $.each( response.message, function( key, value) {
                            errorString += value + "<br>";
                        });
                    }else{
                        errorString = response.message;
                    }
                    Swal.fire(
                        'Error!',
                        errorString,
                        'error'
                    )
                }
            })            

        });
    });    
</script>
@endsection

resources/views/admin/module/setting/edit.blade.php
@extends('admin.layouts.app', ['active' => 'Pengaturan'])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Pengaturan</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('setting.index') }}">Pengaturan</a></li>
            <li class="breadcrumb-item active">Edit</a></li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="nav-icon fas fa-cog"></i> Edit Pengaturan</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('setting.update', $data->id) }}" method="post" class="form-horizontal" id="formData" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="form-group row">
                    <label for="key" class="col-sm-2 col-form-label">Key</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" placeholder="Key" autocomplete="off" value="{{ $data->key }}" disabled>
                    </div>
                </div>

                <div class="form-group row">
                    <label for="value" class="col-sm-2 col-form-label">Tipe</label>
                    <div class="col-sm-10">
                        <input type="text" disabled value="{{ $data->type }}" class="form-control">
                    </div>
                </div>
        
                @if($data->type == 'text')
                <div class="form-group row">
                    <label for="value" class="col-sm-2 col-form-label">Value</label>
                    <div class="col-sm-10">
                        <textarea name="value" id="value" cols="20" rows="5" placeholder="Value" class="form-control">{{ $data->value }}</textarea>
                    </div>
                </div>
                @else
                <div id="type_file" class="form-group row type_value">
                    <label for="value" class="col-sm-2 col-form-label">File</label>
                    <div class="col-sm-10">
                      <input type="file" name="file" id="file" class="form-control">
                    </div>
                </div>
                @endif

                <div class="form-group row">
                    <label for="desc" class="col-sm-2 col-form-label">Deskripsi</label>
                    <div class="col-sm-10">
                      <textarea name="desc" id="desc" cols="20" rows="5" placeholder="Deskripsi" class="form-control">{{ $data->desc }}</textarea>
                    </div>
                </div>

                <div class="float-right">
                    <button id="submit" class="btn btn-success" type="submit">Simpan</button>
                </div>                

            </form> 
        </div>    
    </div>    
    <!-- /.card -->

</section>
<!-- /.content -->
@endsection

@section('javascripts')
<script>
    const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 5000
        });        

    $(document).ready(function(){        

        $('#showPassword').change(function(e){
            if(this.checked)
                $('#password').attr('type','text');
            else
                $('#password').attr('type','password');
        });

        $('#formData').submit(function(e){
            e.preventDefault();            
            $('#submit').attr('disabled', true);
            $('#submit').html('Menyimpan <i class="fas fa-sync-alt fa-spin"></i>');   
            var formData = new FormData($(this)[0]);
            $.ajax({
                method : $(this).attr('method'),
                url : $(this).attr('action'),
                data : formData,
                processData: false,
                contentType: false,
                success : function(data){
                    $('#submit').attr('disabled', false);
                    $('#submit').html('Simpan');
                    Swal.fire(
                        'Selesai!',
                        'Data berhasil disimpan.',
                        'success'
                    )
                    $('#password').attr('type','password');
                    $('#password').val('');
                    $('#showPassword').attr('checked',false)
                },
                error: function(err){
                    $('#submit').attr('disabled', false);
                    $('#submit').html('Simpan');                    
                    var response = JSON.parse(err.responseText);
                    
                    var errorString = '';
                    if(typeof response.message === 'object'){
                        $.each( response.message, function( key, value) {
                            errorString += value + "<br>";
                        });
                    }else{
                        errorString = response.message;
                    }
                    Swal.fire(
                        'Error!',
                        errorString,
                        'error'
                    )
                }
            })            

        });
    });
</script>
@endsection

resources/views/admin/module/setting/index.blade.php
@extends('admin.layouts.app', ['active' => 'Pengaturan'])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Pengaturan</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Pengaturan</li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="float-right mb-3">
        <a href="{{ route('setting.create') }}"><button class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> <span class="d-none d-sm-inline">Tambah Pengaturan</span></button></a>
    </div>
    <div class="clearfix"></div>
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="nav-icon fas fa-cog"></i> List Setting</h3>
            <div class="card-tools">
                <button onclick="$('#tableData').DataTable().ajax.reload();" type="button" class="btn btn-tool" data-toggle="tooltip" title="Refresh">
                    <i class="fas fa-sync"></i></button>                
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped  m-0" id="tableData">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Key</th>
                            <th>Value</th>
                            <th>Status</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>    
    </div>
</section>
<!-- /.content -->
@endsection

@section('javascripts')
    <script>
        $(function() {
            var oTable = $('#tableData').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{ route("setting_getData") }}'
                },
                columns: [              
                {data: 'DT_RowIndex', name: 'DT_RowIndex',searchable:false, orderable: false, width:"10%"},                
                {data: 'key', name: 'key'},
                {data: 'value', name: 'value'},
                {data: 'status', name: 'status', orderable:false},
                {data: 'action', name: 'action', orderable:false, searchable:false, width:"25%"},
                ],                
                "drawCallback": function( settings ) {
                    $("input[data-bootstrap-switch]").each(function(){
                        $(this).bootstrapSwitch('state', $(this).prop('checked'));
                        $(this).on('switchChange.bootstrapSwitch', function (e, state) {
                            Swal.fire({
                                title: 'Sedang mengupdate data..',
                                html: 'Mohon menunggu',
                                onBeforeOpen: () => {
                                    Swal.showLoading();
                            }});
                            $.ajax({
                                type:'post',
                                data:{
                                    id:$(this).data('id'),
                                    status:state,
                                    _token : document.head.querySelector('meta[name="csrf-token"]').content
                                },
                                url: "{{ url('setting/toggleActive') }}", 
                                success: function(result){
                                    Swal.close();
                                    Swal.fire(
                                        'Success!',
                                        `Pengaturan berhasil  ${state?'diaktifkan':'dinonaktifkan'}`,
                                        'success'
                                    )
                                    oTable.ajax.reload(null,false)
                                },
                                error: function(){
                                    Swal.close();
                                    Swal.fire(
                                        'Error!',
                                        `Pengaturan tidak berhasil  ${state?'diaktifkan':'dinonaktifkan'} `,
                                        'error'
                                    )
                                    oTable.ajax.reload(null,false)
                                }   
                            });
                        });
                    });                    
                }
            });            
        });        

        function del(id,nama){
            Swal.fire({
                title: 'Peringatan!',
                text: "Yakin menghapus data "+nama+" ?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batalkan',
                showLoaderOnConfirm: true,
                preConfirm: (del) => {
                    return fetch("{{ url('setting/delete') }}/"+id,{
                    method: 'get',
                    credentials: "same-origin",
                    })
                    .then(response => {
                        if (!response.ok) {
                        throw new Error(response.statusText)
                        }
                        return response.json()
                    })
                    .catch(error => {
                        Swal.showValidationMessage(
                        `Request failed: ${error}`
                        )
                    })
                },
                allowOutsideClick: () => !Swal.isLoading()
                }).then((result) => {                    
                if (result.value) {                    
                    Swal.fire(
                        'Terhapus!',
                        'Data berhasil dihapus',
                        'success'
                    )
                    $('#tableData').DataTable().ajax.reload();
                }
                })
        }
        
    </script>
@endsection

resources/views/admin/module/setting/show.blade.php
@extends('admin.layouts.app', ['active' => 'Pengaturan'])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Pengaturan</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('setting.index') }}">Pengaturan</a></li>
            <li class="breadcrumb-item active">Show</a></li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="float-right mb-3">
        <a href="{{ route('setting.edit', $data->id) }}"><button class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit Pengaturan</button></a>        
    </div>
    <div class="clearfix"></div>
    <!-- Default box -->
    <div class="card">
        <div class="card-header">            
            <h3 class="card-title"><i class="nav-icon fas fa-cog"></i> Detail Pengaturan</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">            
            <div class="table-responsive">
                <table class="table table-hover table-borderless">
                    <tr>                    
                        <th>Key</th>
                        <td>:</td>
                        <td>{{ $data->key }}</td>
                    </tr>
                    <tr>                    
                        <th>Deskripsi</th>
                        <td>:</td>
                        <td>{{ $data->desc }}</td>
                    </tr>
                    <tr>                    
                        <th>Value</th>
                        <td>:</td>
                        <td>{{ $data->value }}</td>
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@endsection