routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('profil','ProfileController@index')->name('profil');
Route::get('profil/{page}','ProfileController@index');
Route::get('profil/detail/{id}','ProfileController@detail');

// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::resource('user', 'DataController');
    Route::get('user/delete/{id}', 'DataController@delete');
    Route::get('image/delete/{id}', 'DataController@deleteImage');
    Route::get('file/delete/{id}', 'DataController@deleteFile');
    Route::get('user_getData','DataController@getData')->name('user_getData');

    Route::resource('admin', 'AdminController');
    Route::get('admin/delete/{id}', 'AdminController@delete');
    Route::get('admin_getData','AdminController@getData')->name('admin_getData');

    Route::resource('setting', 'SettingController');
    Route::get('setting/delete/{id}', 'SettingController@delete');
    Route::get('setting_getData','SettingController@getData')->name('setting_getData');
    Route::post('setting/toggleActive','SettingController@toggleActive')->name('setting_toggleActive');

});

resources/views/admin/module/admin/create.blade.php
@extends('admin.layouts.app', ['active' => 'Admin'])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Admin</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Admin</a></li>
            <li class="breadcrumb-item active">Create</a></li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="fa fa-user"></i> Tambah Admin</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('admin.store') }}" method="post" class="form-horizontal" id="formData" enctype="multipart/form-data">
                @csrf                

                <div class="form-group row">
                    <label for="username" class="col-sm-2 col-form-label">Username</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="username" name="username" placeholder="Username" autocomplete="off" value="">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-sm-2 col-form-label">Password</label>
                    <div class="col-sm-10">
                      <input type="password" class="form-control" id="password" name="password" placeholder="Password" autocomplete="off" value="">
                      <small class="form-text text-muted"><i class="fas fa-exclamation-circle"></i>&nbsp;Password minimal terdiri dari 8 karakter</small>
                      <input id="showPassword" type="checkbox"> <label for="showPassword">Lihat Password</label>
                    </div>                    
                </div>
                

                <div class="float-right">
                    <button id="submit" class="btn btn-success" type="submit">Simpan</button>
                </div>

            </form> 
        </div>    
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->


@endsection

@section('javascripts')
<script>
    const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 5000
    });    
    
    $(document).ready(function(){        

        $('#showPassword').change(function(e){
            if(this.checked)
                $('#password').attr('type','text');
            else
                $('#password').attr('type','password');
        });

        $('#formData').submit(function(e){
            e.preventDefault();            
            $('#submit').attr('disabled', true);
            $('#submit').html('Menyimpan <i class="fas fa-sync-alt fa-spin"></i>');   
            var formData = new FormData($(this)[0]);
            $.ajax({
                method : $(this).attr('method'),
                url : $(this).attr('action'),
                data : formData,
                processData: false,
                contentType: false,
                success : function(data){
                    $('#submit').attr('disabled', false);
                    $('#submit').html('Simpan');
                    Swal.fire(
                        'Selesai!',
                        'Data berhasil disimpan.',
                        'success'
                    )
                    $('#formData').trigger("reset");
                    $('#password').attr('type','password');
                },
                error: function(err){
                    $('#submit').attr('disabled', false);
                    $('#submit').html('Simpan');                    
                    var response = JSON.parse(err.responseText);
                    
                    var errorString = '';
                    if(typeof response.message === 'object'){
                        $.each( response.message, function( key, value) {
                            errorString += value + "<br>";
                        });
                    }else{
                        errorString = response.message;
                    }
                    Swal.fire(
                        'Error!',
                        errorString,
                        'error'
                    )
                }
            })            

        });
    });    
</script>
@endsection

resources/views/admin/module/admin/edit.blade.php
@extends('admin.layouts.app', ['active' => 'Admin'])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Admin</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Admin</a></li>
            <li class="breadcrumb-item active">Edit</a></li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">

    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="fa fa-user"></i> Edit Admin</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">
            <form action="{{ route('admin.update', $data->id) }}" method="post" class="form-horizontal" id="formData" enctype="multipart/form-data">
                @csrf
                @method('PUT')

                <div class="form-group row">
                    <label for="username" class="col-sm-2 col-form-label">Username</label>
                    <div class="col-sm-10">
                      <input type="text" class="form-control" id="username" name="username" placeholder="Username" autocomplete="off" value="{{ $data->username }}">
                    </div>
                </div>

                <div class="form-group row">
                    <label for="password" class="col-sm-2 col-form-label">Password Baru</label>
                    <div class="col-sm-10">
                      <input type="password" class="form-control" id="password" name="password" placeholder="Password" autocomplete="off" value="">
                      <small class="form-text text-muted"><i class="fas fa-exclamation-circle"></i>&nbsp;Password minimal terdiri dari 8 karakter. (Kosongkan jika tidak mengganti password)</small>
                      <input id="showPassword" type="checkbox"> <label for="showPassword">Lihat Password</label>
                    </div>                    
                </div>      

                <div class="float-right">
                    <button id="submit" class="btn btn-success" type="submit">Simpan</button>
                </div>                

            </form> 
        </div>    
    </div>    
    <!-- /.card -->

</section>
<!-- /.content -->
@endsection

@section('javascripts')
<script>
    const Toast = Swal.mixin({
            toast: true,
            position: 'top-end',
            showConfirmButton: false,
            timer: 5000
        });        

    $(document).ready(function(){        

        $('#showPassword').change(function(e){
            if(this.checked)
                $('#password').attr('type','text');
            else
                $('#password').attr('type','password');
        });

        $('#formData').submit(function(e){
            e.preventDefault();            
            $('#submit').attr('disabled', true);
            $('#submit').html('Menyimpan <i class="fas fa-sync-alt fa-spin"></i>');   
            var formData = new FormData($(this)[0]);
            $.ajax({
                method : $(this).attr('method'),
                url : $(this).attr('action'),
                data : formData,
                processData: false,
                contentType: false,
                success : function(data){
                    $('#submit').attr('disabled', false);
                    $('#submit').html('Simpan');
                    Swal.fire(
                        'Selesai!',
                        'Data berhasil disimpan.',
                        'success'
                    )
                    $('#password').attr('type','password');
                    $('#password').val('');
                    $('#showPassword').attr('checked',false)
                },
                error: function(err){
                    $('#submit').attr('disabled', false);
                    $('#submit').html('Simpan');                    
                    var response = JSON.parse(err.responseText);
                    
                    var errorString = '';
                    if(typeof response.message === 'object'){
                        $.each( response.message, function( key, value) {
                            errorString += value + "<br>";
                        });
                    }else{
                        errorString = response.message;
                    }
                    Swal.fire(
                        'Error!',
                        errorString,
                        'error'
                    )
                }
            })            

        });
    });
</script>
@endsection

resources/views/admin/module/admin/index.blade.php
@extends('admin.layouts.app', ['active' => 'Admin'])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Admin</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">Admin</li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="float-right mb-3">
        <a href="{{ route('admin.create') }}"><button class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> <span class="d-none d-sm-inline">Tambah Admin</span></button></a>
    </div>
    <div class="clearfix"></div>
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="fa fa-user"></i> List Admin</h3>
            <div class="card-tools">
                <button onclick="$('#tableData').DataTable().ajax.reload();" type="button" class="btn btn-tool" data-toggle="tooltip" title="Refresh">
                    <i class="fas fa-sync"></i></button>                
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped  m-0" id="tableData">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Username</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>    
    </div>
</section>
<!-- /.content -->
@endsection

@section('javascripts')
    <script>
        $(function() {
            var oTable = $('#tableData').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{ route("admin_getData") }}'
                },
                columns: [              
                {data: 'DT_RowIndex', name: 'DT_RowIndex',searchable:false, orderable: false, width:"10%"},                
                {data: 'username', name: 'username'},
                {data: 'action', name: 'action', orderable:false, searchable:false, width:"25%"},
                ],
            });
            
        });

        function del(id,nama){
            Swal.fire({
                title: 'Peringatan!',
                text: "Yakin menghapus data "+nama+" ?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batalkan',
                showLoaderOnConfirm: true,
                preConfirm: (del) => {
                    return fetch("{{ url('admin/delete') }}/"+id,{
                    method: 'get',
                    credentials: "same-origin",
                    })
                    .then(response => {
                        if (!response.ok) {
                        throw new Error(response.statusText)
                        }
                        return response.json()
                    })
                    .catch(error => {
                        Swal.showValidationMessage(
                        `Request failed: ${error}`
                        )
                    })
                },
                allowOutsideClick: () => !Swal.isLoading()
                }).then((result) => {                    
                if (result.value) {                    
                    Swal.fire(
                        'Terhapus!',
                        'Data berhasil dihapus',
                        'success'
                    )
                    $('#tableData').DataTable().ajax.reload();
                }
                })
        }
        
    </script>
@endsection

resources/views/admin/module/admin/show.blade.php
@extends('admin.layouts.app', ['active' => 'Admin'])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>Admin</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('admin.index') }}">Admin</a></li>
            <li class="breadcrumb-item active">Show</a></li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="float-right mb-3">
        <a href="{{ route('admin.edit', $data->id) }}"><button class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit Admin</button></a>        
    </div>
    <div class="clearfix"></div>
    <!-- Default box -->
    <div class="card">
        <div class="card-header">            
            <h3 class="card-title"><i class="fa fa-user"></i> Detail Admin</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">            
            <div class="table-responsive">
                <table class="table table-hover table-borderless">
                    <tr>                    
                        <th>Username</th>
                        <td>:</td>
                        <td>{{ $data->username }}</td>
                    </tr>
                    <tr>
                        <th>Password</th>
                        <td>:</td>
                        <td>********</td>
                    </tr>                    
                </table>
            </div>
        </div>
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@endsection