routes/web.php
<?php

use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
});

Route::get('profil','ProfileController@index')->name('profil');
Route::get('profil/{page}','ProfileController@index');
Route::get('profil/detail/{id}','ProfileController@detail');

// Auth::routes();
Route::get('login', 'Auth\LoginController@showLoginForm')->name('login');
Route::post('login', 'Auth\LoginController@login');
Route::post('logout', 'Auth\LoginController@logout')->name('logout');

Route::group(['middleware' => ['auth']], function () {
    Route::get('home', 'HomeController@index')->name('home');

    Route::resource('user', 'DataController');
    Route::get('user/delete/{id}', 'DataController@delete');
    Route::get('image/delete/{id}', 'DataController@deleteImage');
    Route::get('file/delete/{id}', 'DataController@deleteFile');
    Route::get('user_getData','DataController@getData')->name('user_getData');

    Route::resource('admin', 'AdminController');
    Route::get('admin/delete/{id}', 'AdminController@delete');
    Route::get('admin_getData','AdminController@getData')->name('admin_getData');

    Route::resource('setting', 'SettingController');
    Route::get('setting/delete/{id}', 'SettingController@delete');
    Route::get('setting_getData','SettingController@getData')->name('setting_getData');
    Route::post('setting/toggleActive','SettingController@toggleActive')->name('setting_toggleActive');

});

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

resources/views/admin/module/user/index.blade.php
@extends('admin.layouts.app', ['active' => $var['title'] ])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>{{ $var['title'] }}</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item active">{{ $var['title'] }}</li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="float-right mb-3">
        <a href="{{ route('user.create') }}"><button class="btn btn-primary btn-sm"><i class="fa fa-plus"></i> <span class="d-none d-sm-inline">Tambah {{ $var['title'] }}</span></button></a>
    </div>
    <div class="clearfix"></div>
    <!-- Default box -->
    <div class="card">
        <div class="card-header">
            <h3 class="card-title"><i class="fa fa-user"></i> List {{ $var['title'] }}</h3>
            <div class="card-tools">
                <button onclick="$('#tableData').DataTable().ajax.reload();" type="button" class="btn btn-tool" data-toggle="tooltip" title="Refresh">
                    <i class="fas fa-sync"></i></button>                
                <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                    <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-striped  m-0" id="tableData">
                    <thead>
                        <tr>
                            <th>No.</th>
                            <th>Profil</th>
                            <th>Nama</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                </table>
            </div>
        </div>    
    </div>
</section>
<!-- /.content -->
@endsection

@section('javascripts')
    <script>
        $(function() {
            var oTable = $('#tableData').DataTable({
                processing: true,
                serverSide: true,
                ajax: {
                    url: '{{ route("user_getData") }}'
                },
                columns: [              
                {data: 'DT_RowIndex', name: 'DT_RowIndex',searchable:false, orderable: false, width:"10%"},
                {data: 'profil', name: 'profil', width:"10%"},
                {data: 'nama', name: 'nama'},
                {data: 'action', name: 'action', orderable:false, searchable:false, width:"25%"},
                ],
            });
            
        });

        function del(id,nama){
            Swal.fire({
                title: 'Peringatan!',
                text: "Yakin menghapus data "+nama+" ?",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#d33',
                cancelButtonColor: '#3085d6',
                confirmButtonText: 'Hapus',
                cancelButtonText: 'Batalkan',
                showLoaderOnConfirm: true,
                preConfirm: (del) => {
                    return fetch("{{ url('user/delete') }}/"+id,{
                    method: 'get',
                    credentials: "same-origin",
                    })
                    .then(response => {
                        if (!response.ok) {
                        throw new Error(response.statusText)
                        }
                        return response.json()
                    })
                    .catch(error => {
                        Swal.showValidationMessage(
                        `Request failed: ${error}`
                        )
                    })
                },
                allowOutsideClick: () => !Swal.isLoading()
                }).then((result) => {                    
                if (result.value) {                    
                    Swal.fire(
                        'Terhapus!',
                        'Data berhasil dihapus',
                        'success'
                    )
                    $('#tableData').DataTable().ajax.reload();
                }
                })
        }
        
    </script>
@endsection

resources/views/admin/module/user/show.blade.php
@extends('admin.layouts.app', ['active' => $var['title']])

@section('content')

<!-- Content Header (Page header) -->
<section class="content-header">
    <div class="container-fluid">
    <div class="row mb-2">
        <div class="col-sm-6">
        <h1>{{ $var['title'] }}</h1>
        </div>
        <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="#">Home</a></li>
            <li class="breadcrumb-item"><a href="{{ route('user.index') }}">{{ $var['title'] }}</a></li>
            <li class="breadcrumb-item active">Show</a></li>
        </ol>
        </div>
    </div>
    </div><!-- /.container-fluid -->
</section>

<!-- Main content -->
<section class="content">
    <div class="float-right mb-3">
        <a href="{{ route('user.edit', $data->id) }}"><button class="btn btn-success btn-sm"><i class="fa fa-edit"></i> Edit {{ $var['title'] }}</button></a>
        {{-- <button class="btn btn-danger btn-sm"><i class="fa fa-trash"></i> Hapus {{ $var['title'] }}</button> --}}
    </div>
    <div class="clearfix"></div>
    <!-- Default box -->
    <div class="card">
        <div class="card-header">            
            <h3 class="card-title"><i class="fa fa-user"></i> Detail {{ $var['title'] }}</h3>

            <div class="card-tools">
            <button type="button" class="btn btn-tool" data-card-widget="collapse" data-toggle="tooltip" title="Collapse">
                <i class="fas fa-minus"></i></button>
            </div>
        </div>
        <div class="card-body">            
            <div class="form-group row">
                <div class="col-12 mb-2">
                    <center>
                        <img height="128" width="128" class="img img-circle" src="{{ $data->profile->path != null ? url("storage/".$data->profile->path) : asset('image/default.png') }}" alt="Foto Profile">
                    </center>
                    <center>
                        <label for="">Foto Profil</label>
                    </center>
                </div>
            </div>
            <div class="table-responsive">
                <table class="table table-hover table-borderless">
                    <tr>                    
                        <th>Nama</th>
                        <td>:</td>
                        <td>{{ $data->nama }}</td>
                    </tr>
                    <tr>
                        <th>Jenis Kelamin</th>
                        <td>:</td>
                        <td>{{ $data->jenis_kelamin == 'L' ? 'Laki - Laki' : 'Perempuan' }}</td>
                    </tr>
                    <tr>
                        <th>Email</th>
                        <td>:</td>
                        <td>{{ $data->email }}</td>
                    </tr>
                    <tr>
                        <th>No Telepon</th>
                        <td>:</td>
                        <td>{{ $data->no_telepon }}</td>
                    </tr>
                    <tr>
                        <th>Tempat Lahir</th>
                        <td>:</td>
                        <td>{{ $data->tempat_lahir }}</td>
                    </tr>
                    <tr>
                        <th>Tanggal Lahir</th>
                        <td>:</td>
                        <td>{{ Carbon\Carbon::parse($data->tanggal_lahir)->format('m/d/Y') }}</td>
                    </tr>
                    <tr>
                        <th>Alamat</th>
                        <td>:</td>
                        <td>{{ $data->alamat ?? '-' }}</td>
                    </tr>
                    <tr>
                        <th>Latitude</th>
                        <td>:</td>
                        <td>{{ $data->latitude ?? '-' }}</td>
                    </tr>
                    <tr>
                        <th>Longitude</th>
                        <td>:</td>
                        <td>{{ $data->longitude ?? '-' }}</td>
                    </tr>
                    @if(count($data->foto_tambahan) > 0)
                    <tr>
                        <th>Foto Tambahan</th>
                        <td>:</td>
                            <td>
                            @foreach ($data->foto_tambahan as $item)
                                <img src="{{ url('storage/'.$item->path) }}" alt="" height="128" width="128">
                            @endforeach
                        </td>
                    </tr>
                    @endif
                    @if(count($data->file) > 0)
                    <tr>
                        <th>File Tambahan</th>
                        <td>:</td>
                        <td>
                            <ol>
                                @foreach ($data->file as $item)
                                    <li>
                                        <a target="_blank" href="{{ url('storage/'.$item->path) }}">{{ $item->name }}</a>
                                    </li>
                                @endforeach
                            </ol>
                        </td>
                    </tr>
                    @endif
                </table>
            </div>
        </div>
    </div>
    <!-- /.card -->

</section>
<!-- /.content -->
@endsection